### ISSUE TITLE
Some annotations of videos are color

### ISSUE THREAD

**Issue by BlueCat7** [sssdddwww2/vspw_dataset_download#2]
Dear author, I download 480P dataset, but I find some masks of videos are color. For example, the ID '2378_yn-TfAzobDI' video's masks are color which index not 0-123, so how to I map this kind of color map to gray masks. Thanks.

**Comment by purse1996** [comment]
Could you tell me how to solve the problem? There are too many color mask folders. 
Thank you very much,
